# Generated by Django 2.0.1 on 2018-03-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20180128_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
